### ISSUE TITLE
How can I download an image with a href download attribute?

### ISSUE THREAD

**Issue by hiroto0011** [RavanH/easy-fancybox#11]
For example, with `<a href="something.jpg" download></a>`, i can't download the image but it shows fancybox. How can I prevent that?

**Comment by RavanH** [comment]
Hi, you can give the link a class="nofancybox" (or nolightbox) attribute to exclude it from autodetection.

**Comment by hiroto0011** [comment]
sorry for late reply, it works, thanks you.

**Comment by RavanH** [comment]
Another approach is be to add `a[download]` to the Exclude field in the Miscellaneous section on Settings > Media. I'll be adding it to the default settings in the next release. Thanks @hiroto0011 for alerting me to this :)
